# Generated by Django 5.2 on 2025-04-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hltv_id', models.PositiveIntegerField(unique=True)),
                ('event', models.CharField(max_length=120)),
                ('datetime_utc', models.DateTimeField()),
                ('best_of', models.CharField(max_length=20)),
                ('opponent', models.CharField(max_length=60)),
                ('maps', models.CharField(max_length=20)),
                ('stars', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hltv_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('image', models.URLField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('summary', models.TextField()),
            ],
        ),
    ]
