# Generated by Django 5.2 on 2025-04-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0002_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='stars',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
